config/routes.rb
ZikaronBasalon::Application.routes.draw do
  mount RailsAdmin::Engine => '/webadmin', as: 'rails_admin'
  post 'webhook', :to => 'webhooks#webhook'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/  do
    get 'my-profile', :to => 'users#profile'

    devise_for :users, controllers: { registrations: 'registrations' } do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    resources :cities do
      collection do
        get :autocomplete_city
        get :autocomplete_country
      end
    end

    resources :managers do
      post :remove_city, on: :member
      post :add_city, on: :member
      get :find_movil, on: :collection
      get :load_movil, on: :member
      get :export_hosts, on: :member
      get :export_witnesses, on: :member
      get :export_guests, on: :member
    end


    resources :regions do
      member do
        put :add_city
        patch :add_city
        get :remove_city
      end
    end

    resources :guests
    resources :sessions, only: [:new, :create]
    resources :users, only: [:new] do
      put :assignrole, on: :member
      put :mark_terms_agreement, on: :collection
    end
    resources :witnesses do
      get :assign, on: :member
      get :unassign, on: :member
      resources :comments
    end

    match 'signup', :to => 'users#new', as: :signup, :via => [:get, :post, :delete, :put]
    match 'logout', :to => 'sessions#destroy', as: :logout, :via => [:get, :post, :delete, :put]

    resources :hosts do
      resources :comments
    end

    resources :invites, only: [:create, :update, :destroy]

    match 'pages/home', :to => 'pages#home', as: :host_search, :via => [:get, :post, :delete, :put]
    match 'pages/host_register_link', :to => 'pages#host_register_link', as: :host_register_link, :via => [:get, :post, :delete, :put]
    get 'pages/privacy_policy'
    get 'pages/welcome'
    post 'pages/missing_terms_agreement'
    root :to => 'pages#welcome'
  end
end

app/controllers/witnesses_controller.rb
class WitnessesController < ApplicationController
  include ApplicationHelper
  # before_action :authenticate_user!
  before_filter :is_authorized, only: [:index, :unassign, :assign, :show]
  before_filter :is_admin, only: [:destroy]
  # GET /witnesses
  # GET /witnesses.json

  def index
    @witnesses = Witness.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @witnesses }
    end
  end

  # GET /witnesses/1
  # GET /witnesses/1.json
  def show
    @witness = Witness.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @witness }
    end
  end

  # GET /witnesses/new
  # GET /witnesses/new.json
  def new
    @witness = Witness.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @witness }
    end
  end

  # GET /witnesses/1/edit
  def edit
    @witness = Witness.find(params[:id])
    render 'new'
  end

  # POST /witnesses
  # POST /witnesses.json
  def create
    @witness = Witness.new(params[:witness])

    respond_to do |format|
      if @witness.save
        #format.html { redirect_to action: "index" }
        format.json { render json: @witness, status: :created, location: @witness }
      else
        #format.html { render action: "new" }
        format.json { render json: @witness.errors, status: :unprocessable_entity }
      end
    end
  end

  def safe_params
    params.require(:witness).permit(
      :full_name,
      :address,
      :city_id,
      :witness_type,
      :language,
      :email,
      :phone,
      :stairs,
      :special_needs,
      :seminar_required,
      :free_text,
      :special_population,
      :contacted,
      :contacted_by_host,
      :available_for_teaming,
      :host_id,
      :concept,
      :can_morning,
      :can_afternoon,
      :can_evening,
      :free_on_day,
      :contact_name,
      :contact_phone,
      :external_assignment,
      :additional_phone,
      :available_day1,
      :available_day2,
      :available_day3,
      :available_day4,
      :available_day5,
      :available_day6,
      :archived,
      :need_to_followup,
      :active_last_year,
      :available_day7,
      :available_day8,
      :available_day9,
      :how_brought
    )
  end

  # PUT /witnesses/1
  # PUT /witnesses/1.json
  def update
    @witness = Witness.find(params[:id])

    respond_to do |format|
      if @witness.update(safe_params)
        format.json { render json: @witness, status: :created, location: @witness }
      else
        format.json { render json: @witness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /witnesses/1
  # DELETE /witnesses/1.json
  def destroy
    @witness = Witness.find(params[:id])
    @witness.destroy
    render :json => { success: true, witness: @witness }
  end

  # GET /witnesses/1/assign
  def assign
    @manager = current_user.meta
    @witness = Witness.find(params[:id])
    @cities = City.where(id: get_city_ids_for_assignment)

    respond_to do |format|
      if @manager.concept
        @hosts = Host.where(concept: @manager.concept, survivor_needed: true)
      else
        @hosts = Host.where(city_id: get_city_ids_for_assignment, survivor_needed: true)
      end

      if params[:floor]
        if params[:floor][0] == '>'
          above_floor = params[:floor][1..-1].to_i
          @hosts = @hosts.where('floor > ?', above_floor)
        else
          floor = params[:floor].to_i
          @hosts = @hosts.where(floor: floor)
        end
      end

      if params[:elevator]
        is_elevator = ActiveRecord::Type::Boolean.new.type_cast_from_user(params[:elevator])
        @hosts = @hosts.where(elevator: is_elevator)
      end

      @hosts = @hosts.where(event_language: params[:event_language]) if params[:event_language]

      if params[:available_day]
        @hosts =
          if params[:available_day] == 'available_day_other'
            know_dates = (1..30).map { |day| available_day_to_available_date("available_day#{day}") }.compact
            @hosts.where.not(event_date: know_dates)
          else
            date = available_day_to_available_date(params[:available_day])
            @hosts.where(event_date: date)
          end
      end

      # Extra Filters replaces @hosts.select statement below
      @hosts = @hosts.where(received_registration_mail: true)
      if query.present?
        @hosts = @hosts.joins(:user, :city)
        @hosts = filter_by_query(@hosts, query)
      end
      @hosts = @hosts.where('witness_id IS NULL')
      # @hosts = @hosts.select { |h| h.witness.nil? && h.in_query(query) && h.received_registration_mail }

      page = params[:page]

      @hosts_count = @hosts.count
      @hosts = @hosts.paginate(:page => page || 1, :per_page => 10)


      format.html
      format.json {
        render :json => {
          hosts: @hosts.to_json(:include => [:user, :city]),
          hosts_count: @hosts_count
        }
      }
    end
  end

  def unassign
    @witness = Witness.find(params[:id])
    @host = @witness.host
    @witness.host_id = nil
    @witness.host = nil
    @witness.save!;
    @host.witness_id = nil
    @host.assignment_time = nil
    @host.witness = nil
    @host.contact_witness_sent_at = nil
    @host.save!
    @host_id = @host.id
    ManagerMailer.assignment_cancelled(@host_id, @witness.id, current_user).deliver
    redirect_to @witness
  end

  def is_authorized
    unless (current_user && current_user.meta.is_a?(Manager)) ||
           (current_user && (current_user.admin? || current_user.sub_admin?))
      redirect_to root_path
    end
  end

  def is_admin
    redirect_to root_path unless current_user.admin?
  end

  def get_city_ids_for_assignment
    communities = CommunityLeadership.where(manager_id: current_user.meta.id)
    city_ids = communities.map(&:city_id)
    if params[:city_id]
      [params[:city_id]]
    else
      if !@manager.user.simple_admin?
        City.all.map(&:id)
      else
        @manager.cities.where(id: city_ids).map(&:id)
      end
    end
  end

  def query
    return params[:query]
  end

  private

  def available_day_to_available_date(available_day)
    return nil unless available_day&.start_with?('available_day')

    d_m = I18n.t(available_day, scope: :shared, default: nil)
    Date.strptime("#{d_m}.#{Time.current.to_date.year}", "%d.%m.%Y") if d_m
  end
end

app/helpers/witnesses_helper.rb
module WitnessesHelper
end

app/views/witnesses/_assign_modal.html.erb
<div class="col-xs-12 request-invite">
	<span class="glyphicon glyphicon-remove" ng-click="close()"></span>

	<div class="text-center">
		<h3><%= t '.title' %></h3>
		<p><%= t '.subtitle' %></p>
		<p><%= t '.subtitle_2' %></p>

		<div class="col-xs-12" ng-if="error">
      <div class="alert alert-error" role="alert">
        ציוות נכשל, אנא נסה שנית או בדוק אם קיים כבר שיבוץ למארח זה
      </div>
    </div>

		<div class="col-xs-12">
	  	<div class="row request-container">
	  		<div class="col-xs-6 salon-info-container">
	  			<h5>פרטי המארח</h5>

	  			<div class="salon-info">
	  				<div class="info-group">
		  				<span class="label"><%= t 'shared.name' %>:</span>
		  				<span class="value">{{ host.user.full_name }}</span>
		  			</div>

		  			<div class="info-group">
						<span class="label"><%= t 'shared.address' %>:</span>
						<span class="value">{{ host.address }} {{ host.city.name }}</span>
		  			</div>

		  			<div class="info-group">
						<span class="label"><%= t 'shared.phone' %>:</span>
						<span class="value">{{ host.phone }}</span>
		  			</div>

		  			<div class="info-group">
		  				<span class="label"><%= t 'shared.accessibility' %>:</span>
		  				<span class="value">{{ getAccesability(host) }}</span>
		  			</div>

		  			<div class="info-group">
		  				<span class="label"><%= t 'shared.date' %>:</span>
						<span class="value">{{ formatDate(host.event_date) }} {{ formatTime(host.event_time) }}</span>
		  			</div>

		  			<div class="info-group">
		  				<span class="label"><%= t 'shared.language' %>:</span>
		  				<span class="value">{{ formatLanguage(host.event_language) }}</span>
		  			</div>

		  			<div class="info-group">
		  				<span class="label"><%= t 'shared.free_text' %>:</span>
		  				<span class="value">{{ host.free_text }}</span>
		  			</div>
	  			</div>
	  		</div>

	  		<div class="col-xs-6 salon-info-container">
	  			<h5>פרטי איש העדות</h5>
	  			<div class="salon-info">
	  				<div class="info-group">
		  				<span class="label"><%= t 'shared.name' %>:</span>
		  				<span class="value">{{ witness.full_name }}</span>
		  			</div>

		  			<div class="info-group">
		  				<span class="label"><%= t 'shared.address' %>:</span>
		  				<span class="value">{{ witness.address }} {{ witness.city.name }}</span>
		  			</div>

		  			<div class="info-group">
		  				<span class="label"><%= t 'shared.phone' %>:</span>
		  				<span class="value">{{ witness.phone }}</span>
		  			</div>

		  			<div class="info-group">
		  				<span class="label"><%= t 'shared.accessibility' %>:</span>
		  				<span class="value">{{ formatStairs(witness.stairs) }}</span>
		  			</div>

		  			<div class="info-group">
		  				<span class="label">זמין בשעה:</span>
		  				<span class="value">{{ formatWitnessAvailabilityTime(witness) }}</span>
		  			</div>

		  			<div class="info-group">
		  				<span class="label"><%= t 'shared.language' %>:</span>
		  				<span class="value">{{ formatLanguage(witness.language) }}</span>
		  			</div>

		  			<div class="info-group">
		  				<span class="label"><%= t 'shared.free_text' %>:</span>
		  				<span class="value">{{ witness.free_text }}</span>
		  			</div>
	  			</div>
	  		</div>
	  	</div>
	  </div>

	  <div class="col-xs-12">
	  	<div class="text-center margin-top-10">
	  		<button class="zb-btn btn-orange" ng-click="createAssignment()">
	  			יאללה צוות
	  		</button>
	  	</div>
	  	<div class="text-center margin-top-10">
	  		<button class="zb-btn btn-orange" ng-click="close()">
	  			התחרטתי
	  		</button>
	  	</div>
	  </div>
	</div>
</div>

app/views/witnesses/edit.html.erb
<h1>Editing witness</h1>

<%= render 'form' %>

<%= link_to 'Show', @witness %> |
<%= link_to 'Back', witnesses_path %>

app/views/witnesses/index.html.erb
<div class="col-xs-12" id="witness-index" ng-controller="WitnessIndexController"
     ng-init="init(<%= @witnesses.to_json(:include => :city) %>)">

  <table class="table">
    <thead>
      <tr>
        <th>שם</th>
        <th>עיר</th>
        <th>שפה</th>
        <th>יכול מדרגות</th>
        <th>צריך סמינר</th>
        <th>אוכלוסיה מיוחדת</th>

      </tr> 
    </thead>
    <tbody>
      <tr ng-repeat="witness in witnesses">
        <td>{{ witness.full_name }}</td>
        <td>{{ witness.city.name }}</td>
        <td>{{ witness.language }}</td>
        <td>{{ formatBool(witness.stairs) }}</td>
        <td>{{ formatBool(witness.seminar_required) }}</td>
        <td>{{ formatBool(witness.special_population) }}</td>
      </tr>
    </tbody>
  </table>

</div>

app/views/witnesses/show.html.erb
<div id="witness-show" class="row profile" ng-controller="WitnessShowController"
      ng-init="init(<%= @witness.to_json(:include => [:city, { host: { :include => :user } }, { comments: { :include => :user } }]) %>)">

  <div class="col-xs-12">
    <h1><%= t '.title' %></h1>
  </div>

  <div class="col-xs-8">
    <div class="col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
           <div class="info-title"><%= t 'profile.personal_details' %></div>
           <div>
            <a href="/<%=I18n.locale.to_s%>/witnesses/{{ witness.id }}/edit">
              <%= t 'profile.labels.edit' %>
            </a>
           </div>
        </div>
        <div class="panel-body">

          <div class="field-group">
            <div class="info-label"><%= t 'profile.labels.name' %></div>
            <div>{{ witness.full_name }}</div>
          </div>

          <div class="field-group">
            <div class="info-label"><%= t 'profile.labels.phone' %></div>
            <div>{{ witness.phone }}<br>{{ witness.additional_phone }}</div>
          </div>

          <div class="field-group">
            <div class="info-label"><%= t 'profile.labels.email' %></div>
            <div>{{ witness.email }}</div>
          </div>

          <div class="field-group">
            <div class="info-label"><%= t 'profile.labels.address' %></div>
            <div>{{ witness.address }}</div>
          </div>

          <div class="field-group">
            <div class="info-label">עיר</div>
            <div>{{ witness.city.name }}</div>
          </div>
        </div>

        <div class="panel-body">
          <div class="field-group">
            <div class="info-label"><%= t 'shared.type' %></div>
            <div>{{ formatWitnessType(witness.witness_type) }}</div>
          </div>

          <div class="field-group">
            <div class="info-label">שם איש קשר וקרבה לעד</div>
            <div>{{ witness.contact_name }}</div>
          </div>

          <div class="field-group">
            <div class="info-label">טלפון איש קשר</div>
            <div>{{ witness.contact_phone }}</div>
          </div>

          <div class="field-group">
            <div class="info-label">שפה</div>
            <div>{{ formatLanguage(witness.language) }}</div>
          </div>

          <div class="field-group">
            <div class="info-label"><%= t 'witnesses.new.walk_up_stairs' %></div>
            <div>{{ formatBool(witness.stairs) }}</div>
          </div>
        </div>

        <div class="panel-body">
          <div class="field-group">
            <div class="info-label">צרכים מיוחדים</div>
            <div>{{ witness.special_needs }}</div>
          </div>

          <div class="field-group">
            <div class="info-label">זקוק לסמינר</div>
            <div>{{ formatBool(witness.seminar_required) }}</div>
          </div>

          <div class="field-group">
            <div class="info-label">זמינות</div>
            <div>
              <span ng-if="witness.can_morning" class="margin-left-5">בוקר</span>
              <span ng-if="witness.can_afternoon" class="margin-left-5">צהריים</span>
              <span ng-if="witness.can_evening" class="margin-left-5">ערב</span>
            </div>
          </div>

          <div class="field-group">
            <div class="info-label">אוכלוסיה מיוחדת</div>
            <div>{{ formatBool(witness.special_population) }}</div>
          </div>
        </div>

        <div class="panel-body">
          <div class="field-group">
            <div class="info-label"><%= t "shared.available_days" %></div>
            <span ng-if="witness.available_day1" class="margin-left-5"> <%= t "shared.available_day1" %></span>
            <span ng-if="witness.available_day2" class="margin-left-5"> <%= t "shared.available_day2" %></span>
            <span ng-if="witness.available_day3" class="margin-left-5"> <%= t "shared.available_day3" %></span>
            <span ng-if="witness.available_day4" class="margin-left-5"> <%= t "shared.available_day4" %></span>
            <span ng-if="witness.available_day5" class="margin-left-5"> <%= t "shared.available_day5" %></span>
            <span ng-if="witness.available_day6" class="margin-left-5"> <%= t "shared.available_day6" %></span>
            <span ng-if="witness.available_day7" class="margin-left-5"> <%= t "shared.available_day7" %></span>
            <span ng-if="witness.available_day8" class="margin-left-5"> <%= t "shared.available_day8" %></span>
            <span ng-if="witness.available_day9" class="margin-left-5"> <%= t "shared.available_day9" %></span>
          </div>
        </div>

        <div class="panel-body">
          <div class="field-group">
            <div class="info-label">הערות</div>
            <div>{{ witness.free_text }}</div>
          </div>
        </div>
      </div>
    </div>

    <% if current_user && (current_user.meta.is_a?(Manager) || current_user.admin?) %>
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="info-title">
              <%= t 'hosts.show.manager_actions' %>
            </div>
          </div>
          <div class="panel-body">

            <!-- Host -->
            <div class="field-group">
              <div class="info-label"><%= t 'profile.labels.host' %></div>
              <div ng-if="witness.host" class="cancel-assignment">
                <a ng-href="/<%=I18n.locale.to_s%>/hosts/{{witness.host.id}}">{{ witness.host.user.full_name }}</a>&nbsp;
                <button class="btn btn-warning">
                  <%= link_to 'בטל ציוות', unassign_witness_path(@witness), :confirm => 'בטוח בטוח? למען הסדר הטוב, לאחר ביטול הציוות אנא הוספ/י הערה בדף זה המפרטת את סיבת הביטול.' %>
                </button>
              </div>
              <div ng-if="!witness.host && !witness.external_assignment && !witness.archived && !witness.need_to_followup">
                <%#= t('profile.assign_host') %>
                <%= link_to t('profile.assign_host'), assign_witness_path(@witness) %>
              </div>
              <div ng-if="!witness.host && witness.external_assignment">
                <%= t('profile.labels.external_assignment_explain') %>
                <!-- צוות מחוץ למערכת -->
              </div>
            </div>

            <!-- Concept  - cancelled -->
            <% if current_user && current_user.meta.is_a?(Manager) && false%>
              <div class="field-group">
                <div class="info-label"><%= t 'profile.labels.concept' %></div>
                <div>
                  <select class="form-control"
                          ng-model="witness.concept"
                          ng-options="o.v as o.n for o in [
                            { n: '<%= t 'shared.concept.religious_and_secular' %>', v: 'religious_and_secular' },
                            { n: '<%= t 'shared.concept.vetrans' %>', v: 'vetrans' },
                            { n: '<%= t 'shared.concept.eastern' %>', v: 'eastern' }
                          ]">
                  <option value=""><%= t 'shared.select' %></option>
                </select>
                </div>
              </div>
            <% end %>

            <!-- Type -->
<!--             <div class="form-group ">
                <label for="witness_type" >
                  <%= t 'shared.type' %>
                </label>
                <select class="form-control" id="witness_type"
                        ng-model="witness.witness_type"
                        ng-options="o.v as o.n for o in witnessTypes">
                  <option value=""><%= t 'shared.select' %></option>
                </select>
            </div> -->
          </div>

          <div class="panel-body">
            <!-- External assignment-->
            <% if current_user && current_user.any_admin? %>
              <div class="field-group">
                <div class="info-label">
                  <%= t 'profile.labels.external_assignment' %><br>
                  <div class="checkbox">
                    <label>
                      <input type="checkbox"
                             name="external_assignment"
                             ng-disabled="witness.host || witness.archived || witness.need_to_followup"
                             ng-model="witness.external_assignment"
                             ng-change="confirmExternalAssignment()">
                      <%= t 'profile.labels.external_assignment_explain' %>
                    </label>
                  </div>
                  <div class="checkbox">
                    <label>
                      <input type="checkbox"
                             name="archived"
                             ng-disabled="witness.host || witness.external_assignment || witness.need_to_followup"
                             ng-model="witness.archived"
                             ng-change="confirmArchive()">
                      <%= t 'profile.labels.archived_explain' %>
                    </label>
                  </div>
                  <div class="checkbox">
                    <label>
                      <input type="checkbox"
                             name="need_to_followup"
                             ng-disabled="witness.host || witness.external_assignment || witness.archived"
                             ng-model="witness.need_to_followup"
                             ng-change="confirmFollowup()">
                      <%= t 'profile.labels.need_to_followup_explain' %>
                    </label>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-xs-12">
        <button class="btn btn-warning"
                  ng-click="save()">
          <%= t 'shared.save' %>
        </button>
      </div>

      <div class="col-xs-12" ng-if="success">
        <div class="alert alert-success" role="alert">
          <%= t 'profile.updated' %>
        </div>
      </div>

      <div class="col-xs-12 panel">
          <div comment-form obj="witness" resource="witnesses"
               user-id="<%= current_user.id %>"
               callback="commentCallback"></div>
        </div>
    <% end %>
  </div>

  <% if current_user && current_user.meta.is_a?(Manager) %>
    <div class="col-xs-4">
      <div comment-list comments="witness.comments"/></div>
    </div>
  <% end %>
</div>