config/routes.rb
ZikaronBasalon::Application.routes.draw do
  mount RailsAdmin::Engine => '/webadmin', as: 'rails_admin'
  post 'webhook', :to => 'webhooks#webhook'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/  do
    get 'my-profile', :to => 'users#profile'

    devise_for :users, controllers: { registrations: 'registrations' } do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    resources :cities do
      collection do
        get :autocomplete_city
        get :autocomplete_country
      end
    end

    resources :managers do
      post :remove_city, on: :member
      post :add_city, on: :member
      get :find_movil, on: :collection
      get :load_movil, on: :member
      get :export_hosts, on: :member
      get :export_witnesses, on: :member
      get :export_guests, on: :member
    end


    resources :regions do
      member do
        put :add_city
        patch :add_city
        get :remove_city
      end
    end

    resources :guests
    resources :sessions, only: [:new, :create]
    resources :users, only: [:new] do
      put :assignrole, on: :member
      put :mark_terms_agreement, on: :collection
    end
    resources :witnesses do
      get :assign, on: :member
      get :unassign, on: :member
      resources :comments
    end

    match 'signup', :to => 'users#new', as: :signup, :via => [:get, :post, :delete, :put]
    match 'logout', :to => 'sessions#destroy', as: :logout, :via => [:get, :post, :delete, :put]

    resources :hosts do
      resources :comments
    end

    resources :invites, only: [:create, :update, :destroy]

    match 'pages/home', :to => 'pages#home', as: :host_search, :via => [:get, :post, :delete, :put]
    match 'pages/host_register_link', :to => 'pages#host_register_link', as: :host_register_link, :via => [:get, :post, :delete, :put]
    get 'pages/privacy_policy'
    get 'pages/welcome'
    post 'pages/missing_terms_agreement'
    root :to => 'pages#welcome'
  end
end

app/models/region.rb
# == Schema Information
#
# Table name: regions
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  country_id :integer
#

class Region < ActiveRecord::Base
  has_paper_trail
  OTHER_REGION_NAME = 'Other\אחר'
  attr_accessible :name
  attr_accessible :country_id
  validates :name, :presence => true
  validates :country_id, :presence => true
  belongs_to :country, :counter_cache => true
  has_many :cities
  has_many :israel_cities
  has_many :world_cities
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  before_filter :is_admin
  before_filter :correct_manager

  # before_action :authenticate_user!
  def index
    @country_region_dict = {}
    Country.order('regions_count DESC').where('regions_count > 0').each do |country|
      @country_region_dict[country.name] = []
      Region.where(country_id: country.id).each do |region|
        @country_region_dict[country.name].push(region)
      end
    end
    @regions = Region.all
    @cities = City.all #todo remove
  end

  def show
    @region = Region.find(params[:id])
    @guest = session[:guest_id] ? Guest.find(session[:guest_id]) : Guest.new
    @cities = City.where(region_id: params[:id])
  end

  def new
  	@region = Region.new
  end

  def create
    @region = Region.new(params[:region])
    @is_created=true
    if @region.valid?
      @region.save
    else
      @is_created=false
    end

  end

  def add_city
    @is_valid = true
    if params[:city].present? && params[:city][:id].present?
      params[:city][:id].each {|city_id|
        if city_id.present?
          city = City.where(id: city_id).last
          city.region_id = params[:id]
          city.save!
        end
      }

    else
      @is_valid = false
    end
  end

  def remove_city
    City.destroy(params[:city_id])
  end

end

app/helpers/regions_helper.rb
module RegionsHelper
	def send_mail
		client = SendGrid::Client.new do |c|
		  c.api_user = ENV['SENDGRID_USERNAME']
		  c.api_key = ENV['SENDGRID_PASSWORD']
		end
		mail = SendGrid::Mail.new do |m|
		  m.to = 'uriklar@gmail.com'
		  m.from = 'taco@cat.limo'
		  m.subject = 'Hello world!'
		  m.text = 'aaaaa'
		end

		header = Smtpapi::Header.new
		header.add_substitution('--name--', ['Uri'])        # sub = {keep: ['secret']}
		header.add_category("Testing")
		header.add_filter('templates', 'enable', 1)    # necessary for each time the template engine is used
		header.add_filter('templates', 'template_id', '3246d7b3-36c6-4ef0-aee4-d0cb87da4e60')
		mail.smtpapi = header

		puts client.send(mail) 
	end
end

app/views/regions/add_city.erb
<% if @is_valid %>
  <p><%= t 'shared.created_successfully'%></p>
<% else %>
  <p><%= t 'shared.created_failure'%></p>
<% end %>

<p><%= link_to (t "shared.back"), region_path %></p>

app/views/regions/create.html.erb
<% if @is_created %>
  <p><%= t 'shared.created_successfully'%></p>
  <p><%= link_to(t("shared.create_another"), new_region_path) %></p>
<% else %>
  <p><%= t 'shared.created_failure'%></p>
<% end %>

<p><%= link_to (t "shared.back_to_list"), regions_path %></p>

app/views/regions/index.html.erb
<% title "Regions" %>

<% for country_name, region_arr in @country_region_dict %>
  <h3><%= country_name %></h3>
  <table>
    <!--<tr>-->
      <!--<th><%= t 'shared.name' %></th>-->
    <!--</tr>-->
    <% for region in region_arr %>
      <tr>
        <td><%= link_to region.name, region %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<br/>

<p><%= link_to(t("shared.new_link_text"), new_region_path) %></p>

app/views/regions/new.html.erb
<% title "New Region" %>

<%= form_for @region do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label t 'shared.name' %><br />
    <%= f.text_field :name %><br/>
    <%= f.label t 'shared.country' %><br />
    <%= select("region", "country_id", Country.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }) %>
  </p>
  <p><%= f.submit t 'shared.create_button_text'%></p>
<% end %>


<p><%= link_to (t "shared.back_to_list"), regions_path %></p>

app/views/regions/remove_city.erb
<p><%= t 'shared.deleted_succesfully'%></p>
<p><%= link_to (t "shared.back"), region_path %></p>

app/views/regions/show.html.erb
<p>
  <h2><%= @region.country.name + ' - ' + @region.name %></h2>

  <u><h3><%= t '.add_city_title'%> - <%= @region.name %>:</h3></u>

  <%= form_for @region, :url => url_for(:controller => 'regions', :action => 'add_city', :method => :put) do |f| %>
    <%= f.error_messages %>
    <p>
      <%= f.label t 'shared.city' %><br />
      <%= select("city", "id", City.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, { multiple: true}) %>
    </p>
    <p><%= f.submit t 'shared.create_button_text'%></p>
  <% end %>

  <br/>

  <u><h3><%= t '.edit_city_list'%></h3></u>

  <% @cities.each do |c| %>
    <table>
      <tr>
        <td><%= c.name %></td>
        <td>
          &nbsp;&nbsp;<%= link_to (t 'shared.delete'), {:action => 'remove_city', :city_id => c.id }%>
        </td>
      </tr>
    </table>
  <% end %>


</p>

<br/>
<br/>

<p><%= link_to (t "shared.back_to_list"), regions_path %></p>