config/routes.rb
ZikaronBasalon::Application.routes.draw do
  mount RailsAdmin::Engine => '/webadmin', as: 'rails_admin'
  post 'webhook', :to => 'webhooks#webhook'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/  do
    get 'my-profile', :to => 'users#profile'

    devise_for :users, controllers: { registrations: 'registrations' } do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    resources :cities do
      collection do
        get :autocomplete_city
        get :autocomplete_country
      end
    end

    resources :managers do
      post :remove_city, on: :member
      post :add_city, on: :member
      get :find_movil, on: :collection
      get :load_movil, on: :member
      get :export_hosts, on: :member
      get :export_witnesses, on: :member
      get :export_guests, on: :member
    end


    resources :regions do
      member do
        put :add_city
        patch :add_city
        get :remove_city
      end
    end

    resources :guests
    resources :sessions, only: [:new, :create]
    resources :users, only: [:new] do
      put :assignrole, on: :member
      put :mark_terms_agreement, on: :collection
    end
    resources :witnesses do
      get :assign, on: :member
      get :unassign, on: :member
      resources :comments
    end

    match 'signup', :to => 'users#new', as: :signup, :via => [:get, :post, :delete, :put]
    match 'logout', :to => 'sessions#destroy', as: :logout, :via => [:get, :post, :delete, :put]

    resources :hosts do
      resources :comments
    end

    resources :invites, only: [:create, :update, :destroy]

    match 'pages/home', :to => 'pages#home', as: :host_search, :via => [:get, :post, :delete, :put]
    match 'pages/host_register_link', :to => 'pages#host_register_link', as: :host_register_link, :via => [:get, :post, :delete, :put]
    get 'pages/privacy_policy'
    get 'pages/welcome'
    post 'pages/missing_terms_agreement'
    root :to => 'pages#welcome'
  end
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_header.html.erb
<header>
	<div class="right-side">
		<!-- Home link -->
		<%= link_to t('.home'), t('.homepage_url'), class: "home" %>



		<!-- Signed in user -->
		<% if user_signed_in? %>
			<!-- User profile -->
			<%= link_to(profile_label(current_user), polymorphic_path(current_user.meta), class: 'header-link') if current_user.meta %>

			<!-- Admin -->
			<%= link_to(t('.managers'), managers_path, class: 'header-link') if current_user.admin? %>

      <!-- New Admin link - Area Management -->
      <%= link_to(t('.region_managememnt'), regions_path, class: 'header-link') if current_user.admin? && !current_user.simple_admin? %>

		<!-- Non signed in user -->
		<% else %>

      <!-- Buttons for desktop-->
			<%= link_to signup_path(type: 'host') do %>
				<div class="hidden-xs header-btn white"><%= t('.want_to_host') %></div>
			<% end %>

			<%= link_to host_search_path do %>
				<div class="hidden-xs header-btn orange"><%= t('.want_to_guest') %></div>
			<% end %>

      <!--Buttons for mobile-->
      <%= link_to signup_path(type: 'host') do %>
        <div class="hidden-sm hidden-md hidden-lg header-mobile-btn header-btn white"><%= t('.want_to_host_mobile') %></div>
      <% end %>

      <%= link_to host_search_path do %>
        <div class="hidden-sm hidden-md hidden-lg header-mobile-btn header-btn orange"><%= t('.want_to_guest_mobile') %></div>
      <% end %>

  <% end %>
		<!-- End Non signed in user -->
	</div>

	<div class="left-side">
		<div class="hidden-xs header-brand"><%= t('.brand') %></div>
		<% locale = next_locale(I18n.locale) %>
		<%= link_to locale: locale do %>
      <div onClick="changeLocale('<%=locale.to_str%>')" class="language-btn small-header-btn"><%= locale.capitalize %></div>
		<% end %>
		<% if I18n.locale == :he %>
			<%= link_to "https://www.facebook.com/ZikaronBaSalon/" do %>
				<div class="facebook-btn small-header-btn">f</div>
			<% end %>
		<% end %>

		<!-- Signin/Signout -->
		<% if user_signed_in? %>
      <span class="hidden-xs">
        			שלום <%= current_user.full_name %>
      </span>
			<%= link_to t('.signout'), destroy_user_session_path, method: :delete, class: 'header-link' %>
			<%= link_to t('.admin_db'), rails_admin_path, class: 'header-link' if current_user.admin? %>
    <% else %>
			<%= link_to t('.signin'), user_session_path, class: 'header-link' %>
		<% end %>
	</div>
</header>

<script type="text/javascript">
    function setCookie(name,value,days) {
        var expires = "";
        if (days) {
            var date = new Date();
            date.setTime(date.getTime() + (days*24*60*60*1000));
            expires = "; expires=" + date.toUTCString();
        }
        document.cookie = name + "=" + (value || "")  + expires + "; path=/";
    }

    function changeLocale(locale) {
        setCookie('locale', locale, 100000000);
    }

</script>

app/views/layouts/_header_bootstrap.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
      				data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" a
      				ria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('.home'), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <!-- Signed in user -->
        <% if user_signed_in? %>
          <!-- User profile -->
      	 	<% if current_user.meta %>
        		<li><%= link_to t('.profile'), polymorphic_path(current_user.meta) %></li>
      		<% end %>
          <!-- Admin -->
        	<% if current_user.admin? %>
	        	<li><%= link_to t('.managers'), managers_path %></li>
	        <% end %>

        <!-- Not signed in user -->
        <% else %>
						<li class="header-btn"><%= link_to t('.want_to_host'), signup_path(type: 'host') %></li>
				<% end %>

      </ul>


      <ul class="nav navbar-nav navbar-left">
      	<% if user_signed_in? %>
					<li class="button-link">
						<%= link_to destroy_user_session_path, method: :delete  do %>
							<button class="btn btn-warning"><%= t('.signout') %></button>
						<% end %>
					</li>
				<% else %>
					<li class="button-link">
						<%= link_to user_session_path do %>
							<button class="btn btn-warning"><%= t('.signin') %></button>
						<% end %>
					</li>
				<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/mailer_default.html.erb
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style>
/* -------------------------------------
    GLOBAL
------------------------------------- */
* {
  font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
  font-size: 100%;
  line-height: 1.6em;
  margin: 0;
  padding: 0;
}

img {
  max-width: 600px;
  width: auto;
}

body {
  -webkit-font-smoothing: antialiased;
  height: 100%;
  -webkit-text-size-adjust: none;
  width: 100% !important;
}


/* -------------------------------------
    ELEMENTS
------------------------------------- */
a {
  color: #348eda;
}

.btn-primary {
  Margin-bottom: 10px;
  width: auto !important;
}

.btn-primary td {
  background-color: #348eda;
  border-radius: 25px;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
  font-size: 14px;
  text-align: center;
  vertical-align: top;
}

.btn-primary td a {
  background-color: #348eda;
  border: solid 1px #348eda;
  border-radius: 25px;
  border-width: 10px 20px;
  display: inline-block;
  color: #ffffff;
  cursor: pointer;
  font-weight: bold;
  line-height: 2;
  text-decoration: none;
}

.last {
  margin-bottom: 0;
}

.first {
  margin-top: 0;
}

.padding {
  padding: 10px 0;
}


/* -------------------------------------
    BODY
------------------------------------- */
table.body-wrap {
  padding: 20px;
  width: 100%;
}

table.body-wrap .container {
  border: 1px solid #f0f0f0;
}


/* -------------------------------------
    FOOTER
------------------------------------- */
table.footer-wrap {
  clear: both !important;
  width: 100%;
}

.footer-wrap .container p {
  color: #666666;
  font-size: 12px;

}

table.footer-wrap a {
  color: #999999;
}


/* -------------------------------------
    TYPOGRAPHY
------------------------------------- */
h1,
h2,
h3 {
  color: #111111;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
  font-weight: 200;
  line-height: 1.2em;
  margin: 5px 0 5px;
}

h1 {
  font-size: 25px;
}
h2 {
  font-size: 28px;
}
h3 {
  font-size: 22px;
}

p,
ul,
ol {
  font-size: 14px;
  font-weight: normal;
  margin-bottom: 10px;
}

ul li,
ol li {
  margin-left: 5px;
  list-style-position: inside;
}

/* ---------------------------------------------------
    RESPONSIVENESS
------------------------------------------------------ */

/* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
.container {
  clear: both !important;
  display: block !important;
  Margin: 0 auto !important;
  max-width: 600px !important;
}

/* Set the padding on the td rather than the div for Outlook compatibility */
.body-wrap .container {
  padding: 20px;
}

/* This should also be a block element, so that it will fill 100% of the .container */
.content {
  display: block;
  margin: 0 auto;
  max-width: 600px;
}

/* Let's make sure tables in the content area are 100% wide */
.content table {
  width: 100%;
}

</style>
</head>

<body bgcolor="#f6f6f6" dir="<%= @locale === :en ? 'ltr' : 'rtl' %>">

<!-- body -->
<table class="body-wrap" bgcolor="#f6f6f6">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">

      <!-- content -->
      <div class="content">
      <table>
        <tr>
          <td align="left" >
            <% logo_name = @locale == :en ? 'mail_logo_en' : 'mail_logo_he' %>
            <%= email_image_tag(logo_name + '.png') %>
          </td>
        </tr>
        <tr>
          <td>
            <%= yield %>
          </td>
        </tr>
      </table>
      </div>
      <!-- /content -->

    </td>
    <td></td>
  </tr>
</table>
<!-- /body -->

<!-- footer -->
<table class="footer-wrap">
  <tr>
    <td></td>
    <td class="container">

      <!-- content -->
      <div class="content">
        <table>
          <tr>
            <td align="center">
              <tr>
                <td style="padding-left: 10px; text-align: left;">
                  <a href="https://www.facebook.com/ZikaronBaSalon/">
                    <img src="http://zikaronbasalon.herokuapp.com/mail_facebook_icon.png">
                  </a>
                </td>
                <td style="padding-right: 10px;">
                  <a href="http://www.zikaronbasalon.com">
                    <img src="http://zikaronbasalon.herokuapp.com/mail_website_icon.png">
                  </a>
                </td>
              </tr>
            </td>
          </tr>
        </table>
      </div>
      <!-- /content -->
    </td>
    <td></td>
  </tr>
</table>
<!-- /footer -->

</body>
</html>